[auth]
require_auth = false
password = ""

[flourish]
# api_token = ""
# api_url = "https://app.flourish.studio/api/datasets"

[observable]
# api_token = ""
# api_url = "https://api.observablehq.com/datasets"

[aws]
# access_key_id = ""
# secret_access_key = ""
# region = "eu-west-1"